### PR TITLE
#16: New Engine: GraphvizCmdLineEngine

### PR DESCRIPTION
**Pull request by kerkhofsd**

### CODE REVIEW

**Comment by kerkhofsd** [comment]
@nidi3 I created a test for my GraphvizCmdLine engine. Since the dot command is not available on the test executor, this tests fails. What do you suggest as a solution for this problem?

**Comment by nidi3** [comment]
Thinks for the PR, good work.

Just a few comments:
- Would it be possible to just copy a simple mock "dot" file (.bat or .sh) on the filesystem $PATH in order to fix the test?
- Are the 2 apache commons dependencies really needed?
- You introduced a circular dependency between `engine` and `service` packages: `engine.mayUse(model, service, executor);` and `service.mayUse(engine, executor);`

**Comment by kerkhofsd** [comment]
Hi @nidi3 

- `Would it be possible to just copy a simple mock "dot" file (.bat or .sh) on the filesystem $PATH in order to fix the test?`
I created a solution where I mock the CommandExecutor. Hence for the tests, the dot command get's executed by the mock, that just copies the expected output file to the correct folder.
What do you think about this solution? 
- `Are the 2 apache commons dependencies really needed?`
The `commons-lang3` was needed to determine the OS. I removed this dependency.
The `commons-exec` is quite essential in the code to execute the Commands...
- `You introduced a circular dependency between engine and service packages: engine.mayUse(model, service, executor); and service.mayUse(engine, executor)`
Completely agree, I fixed this.

PR Updated, feel free to share your thoughts / comments!

**Comment by nidi3** [comment]
Sorry for the late answer, here are some more things:
- VizJsOptions are not considered, right?
- Is ICommandExecutor really needed, there's only one implementation. If yes, please drop the I
- I see `System.out`s, so I'm going to setup proper logging

**Comment by nidi3** [comment]
logging is in place.

**Comment by kerkhofsd** [comment]
Hi @nidi3, thans for the feedback

- `VizJsOptions are not considered, right?`
Indeed. But with some parsing of the VizJsOptions to the correct command line arguments, this should be possible.
- `Is ICommandExecutor really needed, there's only one implementation. If yes, please drop the I`
You are right, in this case it is not needed
- `I see System.outs, so I'm going to setup proper logging`
I used the logging you provided!

**Comment by nidi3** [comment]
Sounds great. I refactored AbstractGraphvizEngine so that the signature is `String doExecute(String src, Options options);` and there's no need to parse the js call.

**Comment by kerkhofsd** [comment]
PR Updated, Options are now included!

**Comment by nidi3** [comment]
Great, going to merge it.

**Comment by nidi3** [comment]
It's merged. I adjusted some code styling and replaced all `System.out` and `e.printStacktrace()` with logger calls.
I think the handling of `Options.engine` is not quite right, going to fix this.

**Comment by nidi3** [comment]
Sorry, `Options.engine` works perfectly.

**Comment by kerkhofsd** [comment]
Thanks for merging my PR ;-)

**Pull request merged**
