### PR TITLE
Make vizName in Format public.

### PR DESCRIPTION
**Pull request by vanniktech**
I'd like to use the name for generating the proper file here - https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/pull/51. However it's currently not public

### CODE REVIEW

**Comment by nidi3** [comment]
I don't exactly understand why you need this field.
What's you use case?

**Comment by vanniktech** [comment]
I want to know the file ending of the Format that others can define to generate grahpes.

**Comment by nidi3** [comment]
But `vizName` is the format name used by graphviz, not the file ending.
Eg. format `json0`has file ending `json`.

**Comment by vanniktech** [comment]
Isn't that correct though? Otherwise could we add support for having an explicit field that's named file ending which corresponds to the correct file ending?

**Comment by nidi3** [comment]
That's correct and I'm going to add a new file extension field.

**Comment by nidi3** [comment]
Field is added.
`Renderer.toFile` now adds the correct extension if the filename does not contain a `.`.
Does that solve your issue?

**Comment by vanniktech** [comment]
Where can I see the change?

**Comment by nidi3** [comment]
in `classic` branch

**Comment by vanniktech** [comment]
Seems like it does. Thank you. Waiting for the next version then

**Comment by nidi3** [comment]
0.5.2 released

**Pull request closed without merging**
